apiVersion: v1
kind: Service
metadata:
  name: simple-node-server
spec:
  selector:
    app: simple-node-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
